#' Printing the results of CellTrans.
#' 
#' This functions derives and prints the transition probabilities and the predicted equilibrium distribution of the cell state proportions. The variable input contains the read data from the function readExperimentalData().
#' @param input A list with all necessary data for celltrans which can be generated by readExperimentalData().
#' @keywords transition matrix, Matrix process
#' @export

celltransitions <- function(input) {

  
  # Create a file chooser dialog to select the input file
  selected_file <- tclvalue(tkgetOpenFile())
  datapoints <- read_lines(selected_file)
  
  # Determine the separator based on the contents of the file
  separator <- ifelse(grepl(",", datapoints), ",",
                      ifelse(grepl(";", datapoints), ";", " "))
  datapoints <- strsplit(datapoints, separator)[[1]]
  datapoints <- as.numeric(datapoints)
  
  # Print the data points
  print("datapoints: "); print(datapoints)
  # Rest of your code using the datapoints variable
  #timepoints <- dlgList(title = "Data point(s) for estimation", multiple = TRUE, choices = input$timepoints)$res
  trMatrix <- calculate_transitionMatrix(input$experimentalData, input$timepoints, datapoints)
  MC <- new("markovchain", states = input$cell_types, transitionMatrix = trMatrix, name = "Markov Chain")
  

print("Results of CellTrans")
print("################################")
print("used timepoints:")
print(datapoints)
print(MC)
print("predicted equilibrium distribution")
print(steadyStates(MC))
print("##########################################")
}




